# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 10:32
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to='upload_folder', verbose_name='Image here'),
        ),
    ]
